name: PHP Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4' # Change to your required PHP version

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: vendor/bin/phpunit tests
